#!/usr/bin/env python

import sys
import os.path
import logging
import geojson
import StringIO

import mapzen.whosonfirst.utils
import mapzen.whosonfirst.export
import mapzen.whosonfirst.validator

if __name__ == '__main__':

    import optparse
    opt_parser = optparse.OptionParser()

    opt_parser.add_option('-s', '--source', dest='source', action='store', default=None, help='')
    opt_parser.add_option('-i', '--id', dest='id', action='store', default=None, help='')

    opt_parser.add_option('--stdin', dest='stdin', action='store_true', default=False, help='')

    opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is false)')

    options, args = opt_parser.parse_args()

    if options.verbose:	
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    source = os.path.abspath(options.source)
    exporter = mapzen.whosonfirst.export.flatfile(source)

    if options.id:
        id = int(options.id)
        feature = mapzen.whosonfirst.utils.load(source, id)

    elif options.stdin:
        feature = geojson.load(sys.stdin)

    else:
        logging.error("Missing feature or feature ID")
        sys.exit()

    vld = mapzen.whosonfirst.validator.validator()
    rpt = vld.validate_feature(feature)

    if not rpt.ok():
        logging.error("validation failed for feature")

        if options.verbose:	

            fh = StringIO.StringIO()
            rpt.print_report(fh)
            fh.seek(0)
            
            logging.debug(fh.readlines())

        sys.exit()

    exporter.export_feature(feature)
    sys.exit()
